<template>
  <aside v-if="open" class="copilot" aria-label="AI Copilot">
    <header class="head"><div><h3>AI Copilot</h3><p>Gợi ý để bạn xem và chỉnh trước khi gửi.</p></div><button class="icon" title="Đóng Copilot" @click="$emit('close')">×</button></header>
    <div v-if="!conversationId" class="empty">Chọn một hội thoại để dùng AI Copilot.</div>
    <template v-else>
      <div v-if="error" class="error"><span>{{ error }}</span><button @click="generate()">Thử lại</button></div>
      <div v-if="loading" class="loading"><span class="spinner"/> Đang phân tích hội thoại… <button @click="cancel">Hủy</button></div>
      <template v-if="result">
        <section class="signals"><div><b>Intent</b><span>{{ result.intent || 'unknown' }}</span></div><div><b>Emotion</b><span>{{ emotion }}</span></div><div><b>Giai đoạn</b><span>{{ customerStage }}</span></div><div><b>Confidence</b><span>{{ confidence }}%</span></div></section>
        <section class="block"><h4>Tóm tắt hội thoại</h4><p>{{ summary }}</p></section>
        <section v-if="result.missing_information?.length" class="block"><h4>Thông tin còn thiếu</h4><ul><li v-for="item in result.missing_information" :key="item">{{ item }}</li></ul></section>
        <section class="block reply"><h4>Câu trả lời gợi ý</h4><p>{{ result.reply_text }}</p><div class="actions"><button class="primary" :disabled="!result.reply_text" @click="useReply(result.reply_text)">Dùng câu trả lời</button><button @click="useReply(result.reply_text)">Chỉnh sửa</button><button :disabled="loading" @click="generate()">Tạo lại</button></div><div class="style-actions"><button v-for="style in styles" :key="style.key" :disabled="loading" @click="generate(style.key)">{{ style.label }}</button></div></section>
        <section v-if="result.alternative_replies?.length" class="block"><h4>Phương án khác</h4><button v-for="reply in result.alternative_replies" :key="reply" class="alternative" @click="useReply(reply)">{{ reply }}</button></section>
        <section v-if="result.sources?.length" class="block"><h4>Nguồn kiến thức</h4><ul class="sources"><li v-for="source in result.sources" :key="String(source.chunkId || source.documentId)">{{ source.documentTitle || source.sourceName || 'Nguồn nội bộ' }}<small>v{{ source.documentVersion || '?' }}</small></li></ul></section>
        <section class="block"><h4>Hành động đề xuất</h4><div class="action-grid"><button @click="$emit('action', 'followup')">Đặt Follow-up</button><button @click="$emit('action', 'note')">Thêm ghi chú</button><button class="warn" @click="$emit('action', 'handoff')">Chuyển nhân viên</button></div></section>
        <section class="feedback"><button @click="sendFeedback('good')">Đánh giá tốt</button><button @click="sendFeedback('context_mismatch')">Đánh giá sai</button><button class="danger" @click="sendFeedback('incorrect_information')">Báo sai thông tin</button></section>
        <p v-if="result.do_not_send_reason" class="safety">AI không được tự gửi: {{ result.do_not_send_reason }}</p>
      </template>
      <div v-else-if="!loading && !error" class="empty"><p>Copilot chưa tạo gợi ý.</p><button class="primary" @click="generate()">Tạo gợi ý</button></div>
    </template>
  </aside>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import { api } from '@/api/index';
type Style = 'shorter'|'friendlier'|'professional'|'more_sales_focused';
type CopilotResult = { reply_text:string; alternative_replies:string[]; intent:string; tone:string; sources:Array<Record<string, any>>; confidence?:number; confidence_assessment?:{overall_confidence:number}; missing_information:string[]; suggested_actions:string[]; requires_human:boolean; do_not_send_reason:string|null };
const props = defineProps<{ open:boolean; conversationId?:string|null; privateBlocked?:boolean; customerStage?:string }>();
const emit = defineEmits<{ close:[]; action:[kind:string]; feedback:[kind:string, payload?:Record<string, unknown>] }>();
const result=ref<CopilotResult|null>(null), loading=ref(false), error=ref(''); let controller:AbortController|null=null;
const styles:Array<{key:Style;label:string}>=[{key:'shorter',label:'Ngắn hơn'},{key:'friendlier',label:'Thân thiện hơn'},{key:'professional',label:'Chuyên nghiệp hơn'},{key:'more_sales_focused',label:'Chốt sale hơn'}];
const confidence=computed(()=>Math.round(result.value?.confidence_assessment?.overall_confidence ?? (result.value?.confidence||0)*100)); const emotion=computed(()=>result.value?.tone||'neutral'); const customerStage=computed(()=>props.customerStage||'Chưa xác định'); const summary=computed(()=>result.value?.missing_information?.length ? `AI đang cần làm rõ: ${result.value.missing_information.join(', ')}.` : 'Tóm tắt sẽ được bổ sung từ Conversation Context khi tạo gợi ý.');
function cancel(){controller?.abort();controller=null;loading.value=false;}
async function generate(style?:Style){ if(!props.conversationId||loading.value)return; if(props.privateBlocked){error.value='Bạn không có quyền xem nội dung hội thoại riêng tư này.';return;} cancel(); controller=new AbortController();loading.value=true;error.value='';try{const skills=await api.get<{skills:Array<{id:string;key:string}>}>('/ai/copilot/skills',{signal:controller.signal});const skill=skills.data.skills.find(item=>item.key==='general_assistant')||skills.data.skills[0];if(!skill)throw new Error('AI Skill chưa được quản trị viên khởi tạo.');const response=await api.post<CopilotResult>(`/ai/replies/conversations/${props.conversationId}/generate`,{skillId:skill.id,intent:{primary_intent:'unknown',confidence:.5,missing_information:[]},emotion:{emotion:'neutral',confidence:.5,intensity:.1},employeeTone:style},{signal:controller.signal});result.value=response.data;}catch(e:any){if(e?.name==='CanceledError'||e?.code==='ERR_CANCELED')return;error.value=e?.response?.data?.error||e?.message||'Không thể tạo gợi ý AI.';}finally{if(controller){loading.value=false;controller=null;}}}
function sendFeedback(type:string){ if(!result.value)return; emit('feedback',type,{proposedReply:result.value.reply_text,knowledgeRefs:result.value.sources,selectionStatus:'skipped'}); }
function useReply(text:string){if(!text)return; emit('feedback','edited',{proposedReply:result.value?.reply_text||text,finalReply:text,knowledgeRefs:result.value?.sources||[],selectionStatus:'selected'});window.dispatchEvent(new CustomEvent('chat:insert-suggestion',{detail:{text}}));}
watch(()=>props.conversationId,()=>{cancel();result.value=null;error.value='';});onBeforeUnmount(cancel);
defineExpose({generate,cancel});
</script>
<style scoped>
.copilot{position:fixed;z-index:1200;right:16px;top:72px;bottom:16px;width:min(370px,calc(100vw - 32px));overflow:auto;background:#fff;border:1px solid #dbe4f0;border-radius:12px;box-shadow:0 16px 40px #0f172a26;color:#172033}.head{display:flex;justify-content:space-between;gap:10px;padding:15px;border-bottom:1px solid #e2e8f0;position:sticky;top:0;background:#fff;z-index:1}.head h3,.block h4{margin:0;color:#172033}.head p{margin:3px 0 0;font-size:11px;color:#64748b}.icon{border:0;background:transparent;font-size:24px;cursor:pointer;color:#64748b}.signals{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:#e2e8f0;border-bottom:1px solid #e2e8f0}.signals div{background:#f8fafc;padding:9px 12px}.signals b,.signals span{display:block;font-size:11px}.signals b{color:#64748b}.signals span{margin-top:2px;font-weight:650}.block{padding:13px;border-bottom:1px solid #e2e8f0}.block h4{font-size:12px;margin-bottom:8px}.block p,.block li{font-size:12px;line-height:1.45;color:#334155}.block p{margin:0}.block ul{margin:0;padding-left:18px}.reply{background:#f8fbff}.actions,.style-actions,.action-grid,.feedback{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}button{border:1px solid #cbd5e1;background:#fff;border-radius:7px;padding:6px 8px;font:11px inherit;cursor:pointer;color:#334155}button:disabled{opacity:.55;cursor:not-allowed}.primary{border-color:#2563eb;background:#2563eb;color:#fff}.warn{border-color:#f59e0b;color:#92400e}.danger{border-color:#fecaca;color:#b91c1c}.alternative{display:block;width:100%;text-align:left;margin:6px 0;white-space:normal;line-height:1.35}.sources small{margin-left:5px;color:#64748b}.loading,.error,.empty,.safety{margin:12px;padding:10px;border-radius:8px;font-size:12px}.loading{background:#eff6ff;color:#1d4ed8}.error{background:#fee2e2;color:#991b1b;display:flex;justify-content:space-between;gap:8px}.empty{text-align:center;color:#64748b;background:#f8fafc}.safety{background:#fffbeb;color:#92400e}.spinner{display:inline-block;width:11px;height:11px;border:2px solid #93c5fd;border-top-color:#2563eb;border-radius:50%;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:900px){.copilot{top:auto;bottom:0;right:0;width:100%;max-width:none;height:min(70dvh,620px);border-radius:14px 14px 0 0}}
</style>
