import { beforeEach, describe, expect, it, vi } from 'vitest';
const mocks = vi.hoisted(() => { const prisma: any = { conversation: { findFirst: vi.fn() }, friend: { findFirst: vi.fn() }, followupEnrollment: { findMany: vi.fn() }, followupWorkflow: { findMany: vi.fn() }, aiAuditLog: { create: vi.fn() } }; return { prisma, context: vi.fn(), stop: vi.fn(), createWorkflow: vi.fn() }; });
vi.mock('../../src/shared/database/prisma-client.js', () => ({ prisma: mocks.prisma }));
vi.mock('../../src/modules/ai/conversation-context-builder-service.js', () => ({ buildConversationContext: mocks.context, ContextBuilderError: class extends Error { statusCode=403; code='CONVERSATION_ACCESS_DENIED'; } }));
vi.mock('../../src/modules/followup/followup-engine.js', () => ({ stopEnrollment: mocks.stop }));
vi.mock('../../src/modules/followup/followup-service.js', () => ({ createWorkflow: mocks.createWorkflow }));
import { reconcileAiFollowup, suggestAiFollowup } from '../../src/modules/ai/ai-followup-service.js';
const actor = { orgId: 'org-1', userId: 'u-1', role: 'member', privacyUnlocked: true };
function setup(contact:any = {}) { mocks.context.mockResolvedValue({ sources: [{ id: 'messages:m1' }] }); mocks.prisma.conversation.findFirst.mockResolvedValue({ id: 'c-1', zaloAccountId: 'z-1', contactId: 'contact-1', contact: { id: 'contact-1', fullName: 'Lan', crmName: null, tags: [], consentStatus: 'implicit', lastInboundAt: null, lastOutboundAt: null, ...contact } }); mocks.prisma.friend.findFirst.mockResolvedValue({ strangerBlocked: false }); mocks.prisma.followupEnrollment.findMany.mockResolvedValue([]); mocks.prisma.followupWorkflow.findMany.mockResolvedValue([{ id: 'wf-1', name: 'Re-engage', type: 'reengage', maxMessages: 3, minGapMinutes: 1440, stopOnPurchase: true, stopOnTags: [] }]); mocks.prisma.aiAuditLog.create.mockResolvedValue({}); }
describe('AiFollowup', () => { beforeEach(() => { vi.clearAllMocks(); setup(); }); it('suggests a personalized draft using an existing active campaign without enrolling or sending', async () => { const result = await suggestAiFollowup(actor, { conversationId: 'c-1', intent: 'product_inquiry' }); expect(result).toMatchObject({ allowed: true, shouldStop: false, campaign: { id: 'wf-1' } }); expect(result.contentDraft).toContain('Lan'); }); it('stops active enrollments when customer replied', async () => { setup({ lastInboundAt: new Date() }); mocks.prisma.followupEnrollment.findMany.mockResolvedValue([{ id: 'enr-1', startedAt: new Date(Date.now() - 3600000), messagesSent: 1, workflow: { id: 'wf-1', name: 'x', maxMessages: 3, minGapMinutes: 1, status: 'active' } }]); const result = await reconcileAiFollowup(actor, { conversationId: 'c-1', customerDisposition: 'replied' }); expect(result.stopped).toBe(1); expect(mocks.stop).toHaveBeenCalledWith('enr-1', 'replied', expect.any(Object)); }); it('does not suggest follow-up for opt-out customers', async () => { setup({ consentStatus: 'revoked' }); const result = await suggestAiFollowup(actor, { conversationId: 'c-1', intent: 'product_inquiry' }); expect(result).toMatchObject({ allowed: false, shouldStop: true, stopReason: 'do_not_disturb' }); }); });