import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { requireGrant } from '../rbac/rbac-middleware.js';
import { AIErrorHandler } from './core/ai-error-handler.js';
import { prisma } from '../../shared/database/prisma-client.js';
import { KnowledgeBaseError, archiveKnowledgeSource, createKnowledgeDocument, createKnowledgeSource, listKnowledgeSources, publishKnowledgeDocument, reindexKnowledgeDocument, searchKnowledge, updateKnowledgeSource, type KnowledgeActor } from './knowledge-base-service.js';

const settingsEdit = requireGrant('settings', 'edit');
async function requireAdmin(request: FastifyRequest, reply: FastifyReply) { if (!['owner', 'admin'].includes(request.user!.role)) return reply.status(403).send({ error: 'Admin access required', code: 'ADMIN_REQUIRED' }); }
function actor(request: FastifyRequest): KnowledgeActor { return { orgId: request.user!.orgId, userId: request.user!.id, role: request.user!.role }; }
function handle(reply: FastifyReply, error: unknown) { if (error instanceof KnowledgeBaseError) return reply.status(error.statusCode).send({ error: error.message, code: error.code }); const normalized = AIErrorHandler.normalize(error); return reply.status(normalized.statusCode).send({ error: normalized.message, code: normalized.code }); }

export async function knowledgeBaseRoutes(app: FastifyInstance) {
  app.get('/api/v1/ai/knowledge/sources', { preHandler: [settingsEdit, requireAdmin] }, async (request, reply) => { try { const query = request.query as { includeArchived?: string }; return { sources: await listKnowledgeSources(actor(request), query.includeArchived === 'true') }; } catch (error) { return handle(reply, error); } });
  app.post('/api/v1/ai/knowledge/sources', { preHandler: [settingsEdit, requireAdmin] }, async (request, reply) => { try { return await createKnowledgeSource(actor(request), (request.body ?? {}) as any); } catch (error) { return handle(reply, error); } });
  app.patch('/api/v1/ai/knowledge/sources/:sourceId', { preHandler: [settingsEdit, requireAdmin] }, async (request, reply) => { try { return await updateKnowledgeSource(actor(request), (request.params as { sourceId: string }).sourceId, (request.body ?? {}) as any); } catch (error) { return handle(reply, error); } });
  app.delete('/api/v1/ai/knowledge/sources/:sourceId', { preHandler: [settingsEdit, requireAdmin] }, async (request, reply) => { try { return await archiveKnowledgeSource(actor(request), (request.params as { sourceId: string }).sourceId); } catch (error) { return handle(reply, error); } });
  app.get('/api/v1/ai/knowledge/sources/:sourceId/documents', { preHandler: [settingsEdit, requireAdmin] }, async (request, reply) => { try { const sourceId = (request.params as { sourceId: string }).sourceId; const source = (await listKnowledgeSources(actor(request), true)).find((item) => item.id === sourceId); if (!source) return reply.status(404).send({ error: 'Knowledge source not found', code: 'SOURCE_NOT_FOUND' }); const documents = await prisma.aiKnowledgeDocument.findMany({ where: { orgId: request.user!.orgId, sourceId, deletedAt: null }, select: { id: true, title: true, status: true, version: true, lastIndexedAt: true, updatedAt: true }, orderBy: { updatedAt: 'desc' } }); return { documents }; } catch (error) { return handle(reply, error); } });
  app.post('/api/v1/ai/knowledge/sources/:sourceId/documents', { preHandler: [settingsEdit, requireAdmin] }, async (request, reply) => { try { return await createKnowledgeDocument(actor(request), (request.params as { sourceId: string }).sourceId, (request.body ?? {}) as any); } catch (error) { return handle(reply, error); } });
  app.post('/api/v1/ai/knowledge/documents/:documentId/reindex', { preHandler: [settingsEdit, requireAdmin] }, async (request, reply) => { try { return await reindexKnowledgeDocument(actor(request), (request.params as { documentId: string }).documentId); } catch (error) { return handle(reply, error); } });
  app.post('/api/v1/ai/knowledge/documents/:documentId/publish', { preHandler: [settingsEdit, requireAdmin] }, async (request, reply) => { try { return await publishKnowledgeDocument(actor(request), (request.params as { documentId: string }).documentId); } catch (error) { return handle(reply, error); } });
  app.post('/api/v1/ai/knowledge/search/test', { preHandler: [settingsEdit, requireAdmin] }, async (request, reply) => { try { const body = (request.body ?? {}) as { query?: string; limit?: number; includeDraft?: boolean }; return await searchKnowledge(actor(request), body.query ?? '', { limit: body.limit, includeDraft: !!body.includeDraft }); } catch (error) { return handle(reply, error); } });
}
