import { createHash } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { prisma } from '../../shared/database/prisma-client.js';
import { encryptToken, decryptToken } from '../integrations/_shared/token-encryption.util.js';

export type LearningCandidateStatus = 'collected' | 'filtered' | 'pending_review' | 'approved' | 'rejected' | 'published';
export type LearningKind = 'used_reply_pattern' | 'edited_reply_pattern' | 'knowledge_gap' | 'question_pattern' | 'prompt_improvement' | 'skill_improvement' | 'evaluation_case';
export type LearningActor = { orgId: string; userId: string; role: string };
export class LearningEngineError extends Error { constructor(message: string, public readonly statusCode = 400, public readonly code = 'LEARNING_ENGINE_ERROR') { super(message); this.name = 'LearningEngineError'; } }
const sha = (value: string) => createHash('sha256').update(value).digest('hex');
const bytes = (value: string) => new TextEncoder().encode(encryptToken(value));
const sensitivePatterns: Array<[RegExp, string]> = [
  [/\b(?:\+?84|0)(?:\d[ .-]?){8,10}\b/g, '[PHONE_REDACTED]'],
  [/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi, '[EMAIL_REDACTED]'],
  [/\b(?:otp|mã xác thực|password|mật khẩu|token|api[_ -]?key)\s*[:=]?\s*\S+/gi, '[SECRET_REDACTED]'],
  [/\b(?:\d[ -]?){12,19}\b/g, '[NUMBER_REDACTED]'],
];
export function redactLearningText(value: string) { return sensitivePatterns.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value).replace(/\s+/g, ' ').trim(); }
function decrypt(value?: Uint8Array | null) { if (!value?.length) return ''; try { return decryptToken(Buffer.from(value).toString('utf8')); } catch { return ''; } }
function classify(feedback: { type: string; selectionStatus?: string | null; editDistance?: number | null; reasonCode?: string | null }) { if (feedback.type === 'good' || feedback.selectionStatus === 'selected') return { kind: 'used_reply_pattern' as LearningKind, riskTier: 'low' };
  if (feedback.type === 'edited' || feedback.selectionStatus === 'edited' || (feedback.editDistance ?? 0) >= 20) return { kind: 'edited_reply_pattern' as LearningKind, riskTier: 'medium' };
  if (feedback.type === 'incorrect_information' || feedback.type === 'policy_violation') return { kind: 'knowledge_gap' as LearningKind, riskTier: 'high' };
  if (feedback.type === 'context_mismatch' || feedback.type === 'too_pushy') return { kind: 'skill_improvement' as LearningKind, riskTier: 'medium' };
  if (['missing_emotion', 'too_long', 'too_short', 'too_robotic'].includes(feedback.type)) return { kind: 'prompt_improvement' as LearningKind, riskTier: 'medium' };
  return { kind: 'evaluation_case' as LearningKind, riskTier: 'low' };
}
function candidatePayload(feedback: any, kind: LearningKind) { const proposed = redactLearningText(decrypt(feedback.proposedEncrypted)); const final = redactLearningText(decrypt(feedback.finalEncrypted)); const reason = redactLearningText(feedback.reasonCode ?? '');
  return { version: 1, kind, feedbackId: feedback.id, type: feedback.type, selectionStatus: feedback.selectionStatus, proposedReply: proposed || undefined, finalReply: final || undefined, reason: reason || undefined, editDistance: feedback.editDistance ?? undefined, knowledgeRefs: Array.isArray(feedback.knowledgeRefs) ? feedback.knowledgeRefs.slice(0, 10) : [], context: feedback.contextManifest && typeof feedback.contextManifest === 'object' ? feedback.contextManifest : {}, outcome: feedback.outcome && typeof feedback.outcome === 'object' ? feedback.outcome : {} };
}
export async function collectLearningCandidates(actor: LearningActor, options: { limit?: number; since?: Date } = {}) {
  const feedback = await prisma.aiFeedback.findMany({ where: { orgId: actor.orgId, ...(options.since ? { createdAt: { gte: options.since } } : {}) }, orderBy: { createdAt: 'desc' }, take: Math.max(1, Math.min(options.limit ?? 200, 500)), select: { id: true, runId: true, suggestionId: true, type: true, selectionStatus: true, reasonCode: true, editDistance: true, proposedEncrypted: true, finalEncrypted: true, knowledgeRefs: true, contextManifest: true, outcome: true, quoteGenerated: true, orderGenerated: true } });
  let created = 0; let filtered = 0; let duplicates = 0;
  for (const item of feedback) { const { kind, riskTier } = classify(item); const payload = candidatePayload(item, kind); const material = JSON.stringify(payload); const payloadHash = sha(material); const exists = await prisma.aiLearningCandidate.findFirst({ where: { orgId: actor.orgId, payloadHash }, select: { id: true } }); if (exists) { duplicates++; continue; }
    const hasUsableExample = !!(payload.proposedReply || payload.finalReply || payload.reason || (payload.knowledgeRefs as unknown[]).length); const status: LearningCandidateStatus = hasUsableExample ? 'pending_review' : 'filtered';
    await prisma.aiLearningCandidate.create({ data: { orgId: actor.orgId, runId: item.runId ?? null, suggestionId: item.suggestionId ?? null, feedbackId: item.id, kind, status, payloadEncrypted: bytes(material), payloadHash, evidence: [{ feedbackId: item.id, type: item.type, selectionStatus: item.selectionStatus, quoteGenerated: item.quoteGenerated, orderGenerated: item.orderGenerated, redacted: true, collectedBy: actor.userId }] as Prisma.InputJsonValue, riskTier } });
    if (status === 'filtered') filtered++; else created++;
  }
  await prisma.aiAuditLog.create({ data: { orgId: actor.orgId, actorUserId: actor.userId, eventType: 'learning.collect', outcome: 'success', targetType: 'ai_learning_candidate', metadata: { scanned: feedback.length, created, filtered, duplicates, automaticProductionChange: false } } });
  return { scanned: feedback.length, created, filtered, duplicates };
}
export async function listLearningCandidates(orgId: string, options: { status?: string; limit?: number } = {}) { const candidates = await prisma.aiLearningCandidate.findMany({ where: { orgId, ...(options.status ? { status: options.status } : {}) }, orderBy: { createdAt: 'desc' }, take: Math.max(1, Math.min(options.limit ?? 100, 200)), select: { id: true, kind: true, status: true, riskTier: true, payloadEncrypted: true, payloadHash: true, evidence: true, reviewedAt: true, createdAt: true, feedbackId: true } }); return candidates.map((candidate: any) => ({ ...candidate, payload: (() => { const raw = decrypt(candidate.payloadEncrypted); try { return raw ? JSON.parse(raw) : null; } catch { return null; } })(), payloadEncrypted: undefined })); }
const transitions: Record<string, LearningCandidateStatus[]> = { collected: ['filtered', 'pending_review'], filtered: ['pending_review', 'rejected'], pending_review: ['approved', 'rejected'], approved: ['published', 'rejected'], rejected: [], published: [] };
export async function transitionLearningCandidate(actor: LearningActor, candidateId: string, status: LearningCandidateStatus, note?: string) { const candidate = await prisma.aiLearningCandidate.findFirst({ where: { id: candidateId, orgId: actor.orgId } }); if (!candidate) throw new LearningEngineError('Learning candidate not found', 404, 'CANDIDATE_NOT_FOUND'); const oldStatus = candidate.status === 'pending' ? 'pending_review' : candidate.status; if (!(transitions[oldStatus] ?? []).includes(status)) throw new LearningEngineError('Invalid candidate state transition', 409, 'INVALID_TRANSITION'); const raw = decrypt(candidate.payloadEncrypted); const payload = redactLearningText(raw); const evidence = [...(Array.isArray(candidate.evidence) ? candidate.evidence : []), { transition: `${oldStatus}->${status}`, reviewedBy: actor.userId, note: redactLearningText(note ?? '').slice(0, 500), at: new Date().toISOString() }];
  const updated = await prisma.aiLearningCandidate.update({ where: { id: candidateId }, data: { status, reviewedAt: ['approved', 'rejected', 'published'].includes(status) ? new Date() : undefined, evidence: evidence as Prisma.InputJsonValue } });
  if (status === 'approved') await prisma.aiApprovedExample.upsert({ where: { candidateId }, update: { approvedByUserId: actor.userId, reviewRedacted: redactLearningText(note ?? '').slice(0, 1000) || null }, create: { orgId: actor.orgId, candidateId, approvedByUserId: actor.userId, purpose: candidate.kind, inputEncrypted: bytes(payload), inputHash: sha(payload), outputHash: sha('manager-approved'), reviewRedacted: redactLearningText(note ?? '').slice(0, 1000) || null } });
  if (status === 'rejected') await prisma.aiBlockedExample.upsert({ where: { candidateId }, update: { blockedByUserId: actor.userId, reasonCode: 'manager_rejected', reviewRedacted: redactLearningText(note ?? '').slice(0, 1000) || null }, create: { orgId: actor.orgId, candidateId, blockedByUserId: actor.userId, reasonCode: 'manager_rejected', inputHash: candidate.payloadHash, reviewRedacted: redactLearningText(note ?? '').slice(0, 1000) || null } });
  await prisma.aiAuditLog.create({ data: { orgId: actor.orgId, actorUserId: actor.userId, eventType: 'learning.candidate.transition', outcome: status, targetType: 'ai_learning_candidate', targetId: candidateId, inputHash: candidate.payloadHash, metadata: { from: oldStatus, to: status, productionChanged: false, note: redactLearningText(note ?? '').slice(0, 120) || null } } });
  return updated;
}
export async function learningInsights(orgId: string) { const grouped = await prisma.aiFeedback.groupBy({ by: ['type'], where: { orgId }, _count: { _all: true } }); const counts = Object.fromEntries(grouped.map((row: any) => [row.type, row._count._all])); return { feedbackCounts: counts, recommendations: [{ target: 'prompt', condition: (counts.too_robotic ?? 0) + (counts.too_long ?? 0) + (counts.missing_emotion ?? 0), action: 'review_prompt_variant' }, { target: 'knowledge', condition: (counts.incorrect_information ?? 0) + (counts.policy_violation ?? 0), action: 'review_knowledge_source' }, { target: 'skill', condition: (counts.context_mismatch ?? 0) + (counts.too_pushy ?? 0), action: 'review_skill_rules' }, { target: 'evaluation', condition: Object.values(counts).reduce((sum: number, count: any) => sum + Number(count), 0), action: 'generate_reviewed_test_cases' }], automaticProductionChange: false }; }