import type { ConversationContext } from './conversation-context-builder-service.js';
export type PolicyRisk = 'low' | 'medium' | 'high' | 'critical';
export type PolicyViolation = { code: string; risk: PolicyRisk; message: string };
export type PolicyResult = { allowed: boolean; risk_level: PolicyRisk; violations: PolicyViolation[]; corrected_reply: string | null; requires_human: boolean; confidence: number };
export type PolicyInput = { replyText: string; context: ConversationContext; sources: Array<Record<string, any>>; intent?: string; skillKey?: string; requestedActions?: string[] };
const PRICE = /(?:giá\s*(?:là|chỉ|còn)|báo giá|\d+(?:[.,]\d+)?\s*(?:tr|triệu|tỷ|ty|vnđ|vnd|đ))/i;
const POLICY = /(?:chính sách|bảo hành|đổi trả|hoàn tiền|refund|quy định)/i;
const DELIVERY = /(?:giao (?:trong|vào|đến)|nhận hàng (?:trong|vào)|chắc chắn giao|cam kết giao)/i;
const DISCOUNT = /(?:giảm giá|chiết khấu|mã giảm|khuyến mãi|ưu đãi)/i;
const PII = /(?:\b\d{9,12}\b|[\w.+-]+@[\w.-]+\.[a-z]{2,}|\b(?:otp|mật khẩu|password|token|api key|secret|số thẻ)\b)/i;
const INJECTION = /(?:ignore (?:all |previous )?instructions|bỏ qua (?:mọi |các )?(?:hướng dẫn|quy tắc)|tiết lộ (?:prompt|hệ thống|dữ liệu nội bộ)|system prompt|developer message|show.*(?:secret|token))/i;
const ABUSE = /(?:đồ ngu|ngu vãi|cút đi|cut di|chết đi|chet di|lừa đảo hết|lua dao het)/i;
function riskRank(risk: PolicyRisk) { return ({ low: 0, medium: 1, high: 2, critical: 3 })[risk]; }
function sourceTypes(sources: Array<Record<string, any>>) { return new Set(sources.map((source) => source.sourceType ?? source.type).filter(Boolean)); }
function add(violations: PolicyViolation[], code: string, risk: PolicyRisk, message: string) { violations.push({ code, risk, message }); }
function redact(text: string) { return text.replace(/\b\d{9,12}\b/g, '[đã ẩn]').replace(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi, '[đã ẩn]').replace(/\b(?:otp|mật khẩu|password|token|api key|secret|số thẻ)\b[^,.!?]*/gi, '[đã ẩn dữ liệu nhạy cảm]'); }
export function checkReplyPolicy(input: PolicyInput): PolicyResult { const reply = input.replyText ?? ''; const violations: PolicyViolation[] = []; const types = sourceTypes(input.sources); const access = input.context.access; if (!access?.allowed || !access.contentVisible) add(violations, 'CONVERSATION_ACCESS_DENIED', 'critical', 'Không có quyền dùng nội dung hội thoại cho AI.'); if (PII.test(reply)) add(violations, 'PRIVATE_DATA_DISCLOSURE', 'critical', 'Draft có dấu hiệu tiết lộ dữ liệu riêng tư hoặc secret.'); if (INJECTION.test(reply)) add(violations, 'SYSTEM_DATA_DISCLOSURE', 'critical', 'Draft có dấu hiệu tiết lộ prompt, dữ liệu hệ thống hoặc làm theo prompt injection.'); if (ABUSE.test(reply)) add(violations, 'INAPPROPRIATE_CONTENT', 'high', 'Draft có ngôn ngữ xúc phạm hoặc không phù hợp.'); if (PRICE.test(reply) && !types.has('price_list')) add(violations, 'UNSOURCED_PRICE', 'high', 'Giá hoặc báo giá phải có citation từ bảng giá còn hiệu lực.'); if (POLICY.test(reply) && !types.has('policy') && !types.has('warranty')) add(violations, 'UNSOURCED_POLICY', 'high', 'Chính sách, bảo hành, đổi trả phải có citation chính sách còn hiệu lực.'); if (DELIVERY.test(reply) && !types.has('policy')) add(violations, 'UNCONFIRMED_DELIVERY_COMMITMENT', 'high', 'Không được cam kết ngày giao hàng khi chưa có nguồn xác nhận.'); if (DISCOUNT.test(reply) && !input.requestedActions?.includes('approved_discount')) add(violations, 'UNAUTHORIZED_DISCOUNT', 'high', 'AI không được tự giảm giá hoặc cam kết ưu đãi.'); if ((input.intent === 'complaint' || input.intent === 'return_or_refund' || /(?:hoàn tiền|refund|tranh chấp|khiếu nại)/i.test(reply)) && input.skillKey !== 'human_handoff') add(violations, 'COMPLAINT_OR_REFUND_HANDOFF', 'high', 'Khiếu nại, hoàn tiền hoặc tranh chấp cần chuyển nhân viên có thẩm quyền.'); const max = violations.reduce<PolicyRisk>((current, item) => riskRank(item.risk) > riskRank(current) ? item.risk : current, 'low'); const blocked = violations.some((item) => ['critical', 'high'].includes(item.risk)); const needsHuman = blocked || violations.some((item) => item.code === 'COMPLAINT_OR_REFUND_HANDOFF'); let corrected: string | null = null; if (violations.length && !violations.some((item) => item.code === 'CONVERSATION_ACCESS_DENIED')) { const safe = redact(reply).replace(PRICE, 'thông tin giá cần được nhân viên kiểm tra').replace(DELIVERY, 'thời gian giao cần được nhân viên xác nhận').replace(DISCOUNT, 'ưu đãi cần được nhân viên xác nhận'); corrected = safe === reply || !safe.trim() ? 'Dạ em đã ghi nhận. Em xin phép chuyển nhân viên phụ trách kiểm tra và hỗ trợ anh/chị chính xác hơn.' : safe; }
  return { allowed: !blocked, risk_level: max, violations, corrected_reply: corrected, requires_human: needsHuman, confidence: violations.length ? .93 : .86 };
}
