import { Prisma } from '@prisma/client';
import { prisma } from '../../shared/database/prisma-client.js';
import { DEFAULT_SKILL_CATALOG } from './skills/catalog/index.js';
import type { SkillDefinition } from './skills/skill-definition.js';
import { requirePassingEvaluation } from './evaluation-engine-service.js';
export class SkillFrameworkError extends Error { constructor(message: string, public readonly statusCode = 400, public readonly code = 'SKILL_FRAMEWORK_ERROR') { super(message); this.name = 'SkillFrameworkError'; } }
type Actor = { orgId: string; userId: string };
function config(definition: SkillDefinition) { const { key: _key, name: _name, riskTier: _riskTier, ...rest } = definition; return rest; }
function validate(definition: SkillDefinition) { if (!/^[a-z][a-z0-9_]{2,99}$/.test(definition.key)) throw new SkillFrameworkError('Skill key is invalid'); if (!definition.name.trim() || !definition.goal.trim()) throw new SkillFrameworkError('Skill name and goal are required'); if (definition.confidenceThreshold < 0 || definition.confidenceThreshold > 1) throw new SkillFrameworkError('confidenceThreshold must be between 0 and 1'); }
async function audit(actor: Actor, eventType: string, skillId: string, metadata: Record<string, unknown>) { await prisma.aiAuditLog.create({ data: { orgId: actor.orgId, actorUserId: actor.userId, eventType, outcome: 'success', targetType: 'ai_skill', targetId: skillId, metadata: metadata as Prisma.InputJsonValue } }); }
export async function listSkills(orgId: string) { return prisma.aiSkill.findMany({ where: { orgId, deletedAt: null }, orderBy: { name: 'asc' }, select: { id: true, key: true, name: true, handlerType: true, config: true, riskTier: true, createdAt: true, updatedAt: true, prompts: { where: { deletedAt: null }, select: { id: true, key: true, versions: { where: { status: 'production' }, select: { id: true, version: true } } } } } }); }
export async function getSkill(orgId: string, idOrKey: string) { const skill = await prisma.aiSkill.findFirst({ where: { orgId, deletedAt: null, OR: [{ id: idOrKey }, { key: idOrKey }] }, include: { prompts: { where: { deletedAt: null }, include: { versions: { where: { status: 'production' }, select: { id: true, version: true, approvedAt: true } } } } } }); if (!skill) throw new SkillFrameworkError('AI skill not found', 404, 'SKILL_NOT_FOUND'); return skill; }
export async function syncDefaultSkills(actor: Actor) { const created: string[] = []; for (const definition of DEFAULT_SKILL_CATALOG) { validate(definition); const existing = await prisma.aiSkill.findFirst({ where: { orgId: actor.orgId, key: definition.key }, select: { id: true, deletedAt: true } }); if (existing?.deletedAt) { await prisma.aiSkill.update({ where: { id: existing.id }, data: { deletedAt: null, name: definition.name, handlerType: 'skill_definition', config: config(definition), riskTier: definition.riskTier } }); await audit(actor, 'skill.catalog_restored', existing.id, { key: definition.key }); created.push(definition.key); } else if (!existing) { const skill = await prisma.aiSkill.create({ data: { orgId: actor.orgId, key: definition.key, name: definition.name, handlerType: 'skill_definition', config: config(definition), riskTier: definition.riskTier, createdByUserId: actor.userId } }); await audit(actor, 'skill.catalog_seeded', skill.id, { key: definition.key }); created.push(definition.key); } } return { created, catalogSize: DEFAULT_SKILL_CATALOG.length }; }
export async function createSkill(actor: Actor, definition: SkillDefinition) { validate(definition); const skill = await prisma.aiSkill.create({ data: { orgId: actor.orgId, key: definition.key, name: definition.name, handlerType: 'skill_definition', config: config(definition), riskTier: definition.riskTier, createdByUserId: actor.userId } }); await audit(actor, 'skill.created', skill.id, { key: skill.key }); return skill; }
export async function updateSkill(actor: Actor, skillId: string, input: Partial<SkillDefinition>) { const current = await getSkill(actor.orgId, skillId); await requirePassingEvaluation(actor.orgId, 'skill', current.id); const merged = { key: current.key, name: input.name ?? current.name, riskTier: input.riskTier ?? current.riskTier, ...(current.config as object), ...input } as SkillDefinition; validate(merged); const skill = await prisma.aiSkill.update({ where: { id: current.id }, data: { name: merged.name, config: config(merged), riskTier: merged.riskTier } }); await audit(actor, 'skill.updated', skill.id, { key: skill.key }); return skill; }
export async function archiveSkill(actor: Actor, skillId: string) { const skill = await getSkill(actor.orgId, skillId); await prisma.aiSkill.update({ where: { id: skill.id }, data: { deletedAt: new Date() } }); await audit(actor, 'skill.archived', skill.id, { key: skill.key }); return { id: skill.id, archived: true }; }
export async function resolveSkillsForIntent(orgId: string, intent: string, confidence: number) { const skills = await listSkills(orgId); return skills.filter((skill) => { const cfg = skill.config as Partial<SkillDefinition>; return cfg.activation?.intents?.includes(intent) && confidence >= (cfg.confidenceThreshold ?? 1); }); }
