import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { requireGrant } from '../rbac/rbac-middleware.js';
import { AIErrorHandler } from './core/ai-error-handler.js';
import { SkillFrameworkError, archiveSkill, createSkill, getSkill, listSkills, syncDefaultSkills, updateSkill } from './skill-framework-service.js';
const settingsEdit = requireGrant('settings', 'edit');
async function requireAdmin(request: FastifyRequest, reply: FastifyReply) { if (!['owner', 'admin'].includes(request.user!.role)) return reply.status(403).send({ error: 'Admin access required', code: 'ADMIN_REQUIRED' }); }
const guards = [settingsEdit, requireAdmin];
function actor(request: FastifyRequest) { return { orgId: request.user!.orgId, userId: request.user!.id }; }
function fail(reply: FastifyReply, error: unknown) { if (error instanceof SkillFrameworkError) return reply.status(error.statusCode).send({ error: error.message, code: error.code }); const normalized = AIErrorHandler.normalize(error); return reply.status(normalized.statusCode).send({ error: normalized.message, code: normalized.code }); }
export async function skillFrameworkRoutes(app: FastifyInstance) {
  app.get('/api/v1/ai/copilot/skills', async (request, reply) => { try { return { skills: await listSkills(request.user!.orgId) }; } catch (error) { return fail(reply, error); } }); app.get('/api/v1/ai/skills', { preHandler: guards }, async (request, reply) => { try { return { skills: await listSkills(request.user!.orgId) }; } catch (error) { return fail(reply, error); } }); app.post('/api/v1/ai/skills/catalog/sync', { preHandler: guards }, async (request, reply) => { try { return await syncDefaultSkills(actor(request)); } catch (error) { return fail(reply, error); } }); app.get('/api/v1/ai/skills/:id', { preHandler: guards }, async (request, reply) => { try { return await getSkill(request.user!.orgId, (request.params as { id: string }).id); } catch (error) { return fail(reply, error); } }); app.post('/api/v1/ai/skills', { preHandler: guards }, async (request, reply) => { try { return reply.status(201).send(await createSkill(actor(request), request.body as any)); } catch (error) { return fail(reply, error); } }); app.patch('/api/v1/ai/skills/:id', { preHandler: guards }, async (request, reply) => { try { return await updateSkill(actor(request), (request.params as { id: string }).id, request.body as any); } catch (error) { return fail(reply, error); } }); app.delete('/api/v1/ai/skills/:id', { preHandler: guards }, async (request, reply) => { try { return await archiveSkill(actor(request), (request.params as { id: string }).id); } catch (error) { return fail(reply, error); } }); }
