import { createHash } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { prisma } from '../../shared/database/prisma-client.js';
import { encryptToken } from '../integrations/_shared/token-encryption.util.js';
import { buildConversationContext, ContextBuilderError, type ContextActor } from './conversation-context-builder-service.js';
import { searchKnowledge } from './knowledge-base-service.js';

export type ToolMode = 'read_only' | 'draft' | 'approval_required' | 'forbidden';
export type ToolActor = ContextActor;
export type ToolName = 'search_product' | 'get_product_details' | 'get_approved_price' | 'get_customer_profile' | 'get_order_history' | 'create_note_draft' | 'add_tag_draft' | 'create_followup_draft' | 'create_quote_draft' | 'assign_conversation_draft' | 'human_handoff';
export type ToolDefinition = { name: ToolName; mode: ToolMode; timeoutMs: number; idempotent: boolean; requiresConversation: boolean; description: string };
export const AI_TOOL_CATALOG: ToolDefinition[] = [
  { name: 'search_product', mode: 'read_only', timeoutMs: 3000, idempotent: true, requiresConversation: false, description: 'Search approved product knowledge.' },
  { name: 'get_product_details', mode: 'read_only', timeoutMs: 3000, idempotent: true, requiresConversation: false, description: 'Get approved product details.' },
  { name: 'get_approved_price', mode: 'read_only', timeoutMs: 3000, idempotent: true, requiresConversation: false, description: 'Get an effective approved price citation.' },
  { name: 'get_customer_profile', mode: 'read_only', timeoutMs: 3000, idempotent: true, requiresConversation: true, description: 'Get minimal customer profile for an accessible conversation.' },
  { name: 'get_order_history', mode: 'read_only', timeoutMs: 3000, idempotent: true, requiresConversation: true, description: 'Return available order-history summary without exporting data.' },
  { name: 'create_note_draft', mode: 'draft', timeoutMs: 2000, idempotent: true, requiresConversation: true, description: 'Prepare a note; never saves a Note.' },
  { name: 'add_tag_draft', mode: 'draft', timeoutMs: 2000, idempotent: true, requiresConversation: true, description: 'Prepare a tag addition; never changes tags.' },
  { name: 'create_followup_draft', mode: 'draft', timeoutMs: 2000, idempotent: true, requiresConversation: true, description: 'Prepare follow-up; never enrolls customer.' },
  { name: 'create_quote_draft', mode: 'approval_required', timeoutMs: 2000, idempotent: true, requiresConversation: true, description: 'Prepare quote for explicit staff approval.' },
  { name: 'assign_conversation_draft', mode: 'approval_required', timeoutMs: 2000, idempotent: true, requiresConversation: true, description: 'Prepare assignment; never changes owner.' },
  { name: 'human_handoff', mode: 'approval_required', timeoutMs: 2000, idempotent: true, requiresConversation: true, description: 'Prepare handoff for staff approval.' },
];
const forbidden = new Set(['delete_data', 'change_owner', 'change_price', 'refund', 'bulk_export', 'read_private_conversation']);
const definitions = new Map(AI_TOOL_CATALOG.map((tool) => [tool.name, tool]));
const hash = (value: string) => createHash('sha256').update(value).digest('hex');
const encrypt = (value: string) => new TextEncoder().encode(encryptToken(value));
export class ToolCallingError extends Error { constructor(message: string, public readonly statusCode = 400, public readonly code = 'TOOL_CALL_ERROR') { super(message); } }
function object(value: unknown) { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function required(input: Record<string, unknown>, key: string) { const value = input[key]; if (typeof value !== 'string' || !value.trim()) throw new ToolCallingError(`${key} is required`, 400, 'INVALID_TOOL_INPUT'); return value.trim(); }
function preview(name: ToolName, args: Record<string, unknown>) { const text = JSON.stringify(args).replace(/[\r\n]+/g, ' ').slice(0, 300); return `${name}: ${text}`; }
function withTimeout<T>(promise: Promise<T>, timeoutMs: number) { return Promise.race([promise, new Promise<T>((_, reject) => setTimeout(() => reject(new ToolCallingError('Tool timed out', 504, 'TOOL_TIMEOUT')), timeoutMs))]); }
async function accessibleContext(actor: ToolActor, conversationId: string) { try { return await buildConversationContext(actor, conversationId, { maxTokens: 500 }); } catch (error) { if (error instanceof ContextBuilderError) throw error; throw new ToolCallingError('Conversation access denied', 403, 'CONVERSATION_ACCESS_DENIED'); } }
async function readTool(actor: ToolActor, name: ToolName, args: Record<string, unknown>, conversationId?: string) { if (name === 'search_product' || name === 'get_product_details' || name === 'get_approved_price') { const query = required(args, 'query'); const result = await searchKnowledge(actor, query, { limit: name === 'search_product' ? 6 : 3 }); const allowedTypes = name === 'get_approved_price' ? new Set(['price_list']) : new Set(['product', 'price_list', 'faq']); return { results: result.results.filter((row: any) => allowedTypes.has(row.citation?.sourceType)), citationsRequired: true }; }
  const context = await accessibleContext(actor, conversationId!); const conversation = await prisma.conversation.findFirst({ where: { id: conversationId, orgId: actor.orgId }, select: { contactId: true } }); if (!conversation?.contactId) return { available: false, reason: 'No linked customer' };
  if (name === 'get_customer_profile') { const contact = await prisma.contact.findFirst({ where: { id: conversation.contactId, orgId: actor.orgId }, select: { id: true, fullName: true, crmName: true, status: true, tags: true, lastInteractionAt: true } }); return { profile: contact, contextSources: context.sources.map((source) => source.id) }; }
  return { orders: [], available: false, reason: 'Order history integration is not available in this deployment', contextSources: context.sources.map((source) => source.id) };
}
async function draftTool(actor: ToolActor, definition: ToolDefinition, args: Record<string, unknown>, conversationId: string | undefined, runId: string | undefined, idempotencyKey: string | undefined) { if (!conversationId) throw new ToolCallingError('conversationId is required', 400, 'CONVERSATION_REQUIRED'); await accessibleContext(actor, conversationId); if (definition.name === 'create_note_draft') required(args, 'body'); if (definition.name === 'add_tag_draft') required(args, 'tag'); if (definition.name === 'create_followup_draft') required(args, 'dueAt'); if (definition.name === 'create_quote_draft') required(args, 'items'); if (definition.name === 'assign_conversation_draft') required(args, 'assigneeUserId'); if (definition.name === 'human_handoff') required(args, 'reason'); const payload = JSON.stringify({ tool: definition.name, args, conversationId, idempotencyKey: idempotencyKey ?? null }); const payloadHash = hash(payload); if (runId) { const run = await prisma.aiRun.findFirst({ where: { id: runId, orgId: actor.orgId }, select: { id: true } }); if (!run) throw new ToolCallingError('AI run not found', 404, 'AI_RUN_NOT_FOUND'); const existing = await prisma.aiAction.findFirst({ where: { orgId: actor.orgId, runId, type: definition.name, payloadHash, status: 'proposed' }, select: { id: true, status: true } }); if (existing) return { actionId: existing.id, status: existing.status, idempotent: true, mode: definition.mode, preview: preview(definition.name, args) }; const action = await prisma.aiAction.create({ data: { orgId: actor.orgId, runId, conversationId, type: definition.name, status: 'proposed', riskTier: definition.mode === 'draft' ? 'low' : 'high', payloadEncrypted: encrypt(payload), payloadHash, previewRedacted: preview(definition.name, args), requiresApproval: true } }); return { actionId: action.id, status: action.status, idempotent: false, mode: definition.mode, preview: action.previewRedacted }; }
  return { actionId: null, status: 'proposed', idempotent: false, mode: definition.mode, preview: preview(definition.name, args), persistence: 'No AI run supplied; proposal is not persisted as an action.' };
}
export async function executeToolCall(actor: ToolActor, input: { tool: string; args?: unknown; conversationId?: string; runId?: string; idempotencyKey?: string }) { if (forbidden.has(input.tool)) throw new ToolCallingError('This operation is forbidden for AI', 403, 'TOOL_FORBIDDEN'); const definition = definitions.get(input.tool as ToolName); if (!definition) throw new ToolCallingError('Unknown tool', 404, 'TOOL_NOT_FOUND'); const args = object(input.args); if (definition.requiresConversation && !input.conversationId) throw new ToolCallingError('conversationId is required', 400, 'CONVERSATION_REQUIRED'); const result = await withTimeout<any>(definition.mode === 'read_only' ? readTool(actor, definition.name, args, input.conversationId) : draftTool(actor, definition, args, input.conversationId, input.runId, input.idempotencyKey), definition.timeoutMs); await prisma.aiAuditLog.create({ data: { orgId: actor.orgId, actorUserId: actor.userId, runId: input.runId ?? null, conversationId: input.conversationId ?? null, eventType: 'tool.call', outcome: 'success', targetType: 'ai_tool', targetId: definition.name, inputHash: hash(JSON.stringify({ tool: definition.name, args, conversationId: input.conversationId, idempotencyKey: input.idempotencyKey ?? null })), metadata: { mode: definition.mode, timeoutMs: definition.timeoutMs, idempotencyKey: input.idempotencyKey ?? null, rawArgumentsLogged: false } as Prisma.InputJsonValue } }); return { tool: definition.name, mode: definition.mode, result }; }
export { ContextBuilderError };