<template>
  <section class="admin-center">
    <header><div><h2>Trung tâm quản trị AI</h2><p>Giám sát, kiểm soát và triển khai AI theo quyền quản trị.</p></div><div class="actions"><input v-model="from" type="date" @change="load"/><input v-model="to" type="date" @change="load"/><button class="danger" @click="toggleEmergency">{{ emergency ? 'Bỏ dừng khẩn cấp' : 'Dừng khẩn cấp AI' }}</button></div></header>
    <nav class="tabs"><button v-for="item in tabs" :key="item.key" :class="{ active: selected === item.key }" @click="selected = item.key">{{ item.label }}</button></nav>
    <p v-if="error" class="error">{{ error }}</p>
    <template v-if="selected === 'overview'"><div class="metrics"><article v-for="item in cards" :key="item.label"><span>{{ item.label }}</span><strong>{{ item.value }}</strong></article></div><div v-if="summary?.alerts?.length" class="alerts"><p v-for="alert in summary.alerts" :key="alert.code" :class="alert.level">{{ alert.message }}</p></div><div class="split"><section><h3>Ý định phổ biến</h3><p v-for="item in summary?.topIntents ?? []" :key="item.label">{{ item.label }} <b>{{ item.count }}</b></p></section><section><h3>Kho tri thức còn thiếu</h3><strong>{{ summary?.metrics?.knowledgeGaps ?? 0 }}</strong><p>Mục đang chờ xem xét/phê duyệt.</p></section></div></template>
    <template v-else-if="selected === 'audit'"><button @click="loadAudit">Tải audit log</button><div class="logs"><p v-for="log in logs" :key="log.id"><b>{{ log.eventType }}</b> · {{ log.outcome }} · {{ new Date(log.createdAt).toLocaleString('vi-VN') }}</p></div></template>
    <template v-else><section class="placeholder"><h3>{{ current?.label }}</h3><p>{{ current?.description }}</p><p>Chức năng này dùng module AI hiện có và chỉ hiển thị dữ liệu phù hợp quyền quản trị. Không hiển thị secret hoặc payload nhạy cảm.</p></section></template>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { api } from '@/api/index';
const tabs = [{key:'overview',label:'Tổng quan',description:''},{key:'agents',label:'Tác nhân AI',description:'Quản lý tác nhân AI và khả năng.'},{key:'skills',label:'Kỹ năng',description:'Quản lý kỹ năng và quy tắc an toàn.'},{key:'prompts',label:'Lời nhắc',description:'Phiên bản, kiểm thử, áp dụng và khôi phục lời nhắc.'},{key:'knowledge',label:'Kho tri thức',description:'Nguồn, tài liệu, lập chỉ mục và phê duyệt.'},{key:'learning',label:'Học có kiểm soát',description:'Mẫu đã che dữ liệu, chờ xem xét.'},{key:'evaluations',label:'Đánh giá',description:'Ca kiểm thử, lượt chạy, ngưỡng và cổng áp dụng.'},{key:'auto_reply',label:'Tự động trả lời',description:'Chế độ mô phỏng, phạm vi và dừng khẩn cấp.'},{key:'feedback',label:'Phản hồi',description:'Phản hồi nhân viên và kết quả.'},{key:'logs',label:'Nhật ký',description:'Lượt chạy và lỗi đã chuẩn hóa.'},{key:'usage',label:'Sử dụng & Chi phí',description:'Lượng token và chi phí tổng hợp.'},{key:'models',label:'Mô hình',description:'Cấu hình mô hình, không hiển thị khóa.'},{key:'security',label:'Bảo mật',description:'Quyền, riêng tư, chính sách và an toàn công cụ.'},{key:'audit',label:'Kiểm toán',description:'Nhật ký kiểm toán không chứa nội dung nhạy cảm.'},{key:'deploy',label:'Áp dụng & Khôi phục',description:'Chỉ áp dụng sau khi đánh giá đạt; khôi phục qua phiên bản đã duyệt.'}];
const selected=ref('overview'), summary=ref<any>(null), logs=ref<any[]>([]), error=ref(''); const to=ref(new Date().toISOString().slice(0,10)); const from=ref(new Date(Date.now()-29*86400000).toISOString().slice(0,10)); const current=computed(()=>tabs.find(t=>t.key===selected.value)); const emergency=computed(()=>!!summary.value?.alerts?.some((a:any)=>a.code==='EMERGENCY_STOP_ACTIVE'));
const cards=computed(()=>{const m=summary.value?.metrics??{};return [{label:'AI xử lý',value:m.aiProcessed??0},{label:'Gợi ý',value:m.suggestions??0},{label:'Nhân viên dùng',value:m.employeeUsed??0},{label:'Tỷ lệ sửa',value:`${m.editRate??0}%`},{label:'Tự gửi',value:m.autoSent??0},{label:'Handoff',value:m.handoffs??0},{label:'Tỷ lệ lỗi',value:`${m.errorRate??0}%`},{label:'Hallucination',value:`${m.hallucinationRate??0}%`},{label:'Chi phí (µ)',value:m.costMicros??'0'}]});
async function load(){try{error.value='';const r=await api.get('/ai/admin-center/summary',{params:{from:from.value,to:to.value}});summary.value=r.data}catch(e:any){error.value=e?.response?.data?.error||'Không tải được Trung tâm quản trị AI'}} async function loadAudit(){try{const r=await api.get('/ai/admin-center/audit',{params:{from:from.value,to:to.value}});logs.value=r.data.logs}catch(e:any){error.value=e?.response?.data?.error||'Không tải được audit'}} async function toggleEmergency(){if(!confirm(emergency.value?'Bỏ dừng khẩn cấp?':'Dừng toàn bộ Auto Reply?'))return;try{await api.post('/ai/admin-center/emergency-stop',{enabled:!emergency.value});await load()}catch(e:any){error.value=e?.response?.data?.error||'Không cập nhật được emergency stop'}} onMounted(load);
</script>
<style scoped>.admin-center{margin-bottom:20px;background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:16px}.admin-center header,.actions,.tabs,.split{display:flex;gap:8px}.admin-center header{justify-content:space-between;align-items:flex-start}.admin-center h2{font-size:16px;margin:0}.admin-center p{font-size:12px;color:#64748b}.actions{flex-wrap:wrap}.actions input,.actions button,.tabs button,.placeholder button{font-size:12px;padding:6px 8px;border:1px solid #cbd5e1;border-radius:6px;background:#fff}.danger{color:#b91c1c;border-color:#fecaca!important}.tabs{overflow:auto;margin:14px 0;border-bottom:1px solid #e2e8f0;padding-bottom:8px}.tabs button{white-space:nowrap;border:0}.tabs .active{background:#dbeafe;color:#1d4ed8}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(105px,1fr));gap:8px}.metrics article,.split section{background:#f8fafc;border-radius:7px;padding:10px}.metrics span{display:block;font-size:11px;color:#64748b}.metrics strong{font-size:18px}.alerts p{padding:8px;border-radius:6px}.alerts .warning{background:#fef3c7;color:#92400e}.alerts .critical{background:#fee2e2;color:#991b1b}.split{margin-top:10px}.split section{flex:1}.split p{display:flex;justify-content:space-between}.logs{max-height:280px;overflow:auto}.error{color:#b91c1c}.placeholder{padding:14px;background:#f8fafc;border-radius:7px}@media(max-width:700px){.admin-center header{flex-direction:column}.split{flex-direction:column}}</style>