<template>
  <section class="security-panel">
    <header><div><h3>Bảo mật & kiểm soát</h3><p>Trạng thái quyền truy cập, riêng tư, công cụ và các cổng an toàn AI.</p></div><button :disabled="loading" @click="load"><span class="mdi mdi-refresh"/> Làm mới</button></header>
    <div v-if="error" class="state error">{{ error }}</div><div v-else-if="loading" class="state">Đang kiểm tra chính sách…</div>
    <template v-else-if="data">
      <div class="runtime"><article><span>Auto Reply</span><strong :class="data.runtime.autoReply.emergencyStop?'danger':'ok'">{{ data.runtime.autoReply.emergencyStop?'Đã dừng khẩn cấp':data.runtime.autoReply.mode }}</strong></article><article><span>Release Production</span><strong>{{ data.runtime.productionReleases }}</strong></article><article><span>Tài liệu Published</span><strong>{{ data.runtime.publishedKnowledge }}</strong></article><article><span>Audit 30 ngày</span><strong>{{ data.runtime.auditEventsLast30Days }}</strong></article></div>
      <section class="card"><h4>Cổng bảo vệ đang áp dụng</h4><div class="safeguards"><article v-for="item in data.safeguards" :key="item.key"><span class="mdi" :class="item.status==='blocked'?'mdi-alert-circle-outline':'mdi-shield-check-outline'"/><div><strong>{{ item.label }}</strong><small>{{ status(item.status) }}</small></div><i :class="item.status"/></article></div></section>
      <div class="two-col"><section class="card"><h4>Ma trận quyền AI</h4><div class="permissions"><article v-for="item in data.permissions" :key="item.resource"><strong>{{ item.resource }}</strong><div><span v-for="action in item.actions" :key="action">{{ action }}</span></div></article></div></section><section class="card"><h4>Model và chính sách dữ liệu</h4><div class="models"><article v-for="model in data.models" :key="model.id"><div><strong>{{ model.name }}</strong><small>{{ model.provider }} · {{ model.model }}</small></div><span :class="{warn:!model.fallbackModelConfigId}">{{ model.fallbackModelConfigId?'Có fallback':'Chưa có fallback' }}</span></article><p v-if="!data.models.length">Chưa có model active hoặc approved.</p></div></section></div>
      <section class="recommend"><span class="mdi mdi-information-outline"/><div><strong>Nguyên tắc vận hành</strong><p>Chỉ mở Auto Reply sau khi có Release Production, tài liệu đã Publish, Evaluation đạt và đã quan sát đủ dữ liệu ở chế độ mô phỏng.</p></div></section>
    </template>
  </section>
</template>
<script setup lang="ts">
import { onMounted,ref } from 'vue';import { api } from '@/api/index';type Data={safeguards:Array<{key:string;label:string;status:string}>;permissions:Array<{resource:string;actions:string[]}>;models:Array<{id:string;name:string;provider:string;model:string;status:string;fallbackModelConfigId:string|null}>;runtime:{autoReply:{enabled:boolean;mode:string;emergencyStop:boolean};productionReleases:number;publishedKnowledge:number;auditEventsLast30Days:number}};const data=ref<Data|null>(null),loading=ref(false),error=ref('');const status=(v:string)=>({enforced:'Đang bắt buộc',ready:'Sẵn sàng',blocked:'Chưa đạt điều kiện'} as Record<string,string>)[v]||v;async function load(){loading.value=true;error.value='';try{data.value=(await api.get<Data>('/ai/admin-center/security')).data}catch(e:any){error.value=e?.response?.data?.error||'Không thể tải trạng thái bảo mật'}finally{loading.value=false}}onMounted(load);
</script>
<style scoped>
.security-panel{display:grid;gap:16px}.security-panel>header{display:flex;justify-content:space-between;gap:16px}.security-panel h3{margin:0;font-size:20px;color:#172033}.security-panel header p{margin:5px 0 0;color:#64748b}.security-panel header button{border:1px solid #cbd5e1;border-radius:8px;background:#fff;padding:9px 12px;color:#334155;cursor:pointer}.state{padding:24px;border:1px dashed #cbd5e1;border-radius:10px;text-align:center;color:#64748b}.state.error{border-color:#fecaca;background:#fff1f2;color:#991b1b}.runtime{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.runtime article{display:grid;gap:6px;padding:14px;border:1px solid #e2e8f0;border-radius:10px}.runtime span{color:#64748b}.runtime strong{font-size:20px}.runtime .danger{color:#b91c1c}.runtime .ok{color:#15803d}.card{overflow:hidden;border:1px solid #e2e8f0;border-radius:10px;background:#fff}.card h4{margin:0;padding:13px 15px;border-bottom:1px solid #e2e8f0}.safeguards{display:grid;grid-template-columns:1fr 1fr;gap:0}.safeguards article{display:grid;grid-template-columns:30px 1fr 10px;align-items:center;gap:10px;padding:13px 15px;border-bottom:1px solid #f1f5f9}.safeguards .mdi{font-size:22px;color:#2563eb}.safeguards div{display:grid;gap:3px}.safeguards small{color:#64748b}.safeguards i{width:9px;height:9px;border-radius:50%;background:#16a34a}.safeguards i.blocked{background:#f59e0b}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:14px}.permissions article{display:grid;grid-template-columns:130px 1fr;gap:10px;padding:12px 15px;border-bottom:1px solid #f1f5f9}.permissions div{display:flex;gap:6px;flex-wrap:wrap}.permissions span{padding:3px 7px;border-radius:999px;background:#eff6ff;color:#1d4ed8}.models article{display:flex;justify-content:space-between;gap:12px;padding:12px 15px;border-bottom:1px solid #f1f5f9}.models div{display:grid;gap:4px}.models small{color:#64748b}.models article>span{align-self:center;padding:4px 7px;border-radius:999px;background:#dcfce7;color:#166534}.models article>span.warn{background:#fef3c7;color:#92400e}.models p{padding:0 15px;color:#64748b}.recommend{display:flex;gap:11px;padding:14px;border-radius:10px;background:#eff6ff;color:#1e40af}.recommend .mdi{font-size:23px}.recommend p{margin:4px 0 0;line-height:1.5}@media(max-width:900px){.runtime,.safeguards,.two-col{grid-template-columns:1fr 1fr}}@media(max-width:600px){.runtime,.safeguards,.two-col{grid-template-columns:1fr}}
</style>
