<template>
  <section class="usage-panel">
    <header class="panel-head"><div><h3>Sử dụng & chi phí</h3><p>Theo dõi token, độ trễ và chi phí theo model, tác vụ và ngày.</p></div><button :disabled="loading" @click="load"><span class="mdi mdi-refresh" /> Làm mới</button></header>
    <div class="filters"><label>Từ ngày<input v-model="from" type="date" /></label><label>Đến ngày<input v-model="to" type="date" /></label><button @click="load">Áp dụng</button></div>
    <div v-if="error" class="state error">{{ error }}</div><div v-else-if="loading" class="state">Đang tổng hợp dữ liệu…</div>
    <template v-else-if="data">
      <div class="metrics"><article><span>Lượt gọi model</span><strong>{{ number(data.totals.requests) }}</strong></article><article><span>Tổng token</span><strong>{{ number(data.totals.inputTokens+data.totals.outputTokens) }}</strong><small>{{ number(data.totals.cachedInputTokens) }} cached</small></article><article><span>Chi phí</span><strong>{{ cost(data.totals.costMicros) }}</strong></article><article><span>Độ trễ P50</span><strong>{{ latency(data.totals.p50LatencyMs) }}</strong></article><article><span>Độ trễ P95</span><strong>{{ latency(data.totals.p95LatencyMs) }}</strong></article><article><span>Lỗi provider</span><strong>{{ number(data.totals.errors) }}</strong></article></div>
      <div v-if="!data.hasData" class="state"><strong>Chưa có dữ liệu sử dụng</strong><span>Dữ liệu sẽ xuất hiện sau khi Copilot gọi model qua pipeline mới.</span></div>
      <div v-else class="grids">
        <section><h4>Theo model</h4><div class="table"><div class="row head"><span>Model</span><span>Lượt gọi</span><span>Token</span><span>P95</span><span>Chi phí</span></div><div v-for="item in data.byModel" :key="item.name" class="row"><strong>{{ item.name }}</strong><span>{{ number(item.requests) }}</span><span>{{ number(item.inputTokens+item.outputTokens) }}</span><span>{{ latency(item.p95LatencyMs) }}</span><span>{{ cost(item.costMicros) }}</span></div></div></section>
        <section><h4>Theo tác vụ</h4><div class="table"><div class="row task head"><span>Tác vụ</span><span>Lượt gọi</span><span>Token</span><span>Chi phí</span></div><div v-for="item in data.byTask" :key="item.name" class="row task"><strong>{{ item.name }}</strong><span>{{ number(item.requests) }}</span><span>{{ number(item.inputTokens+item.outputTokens) }}</span><span>{{ cost(item.costMicros) }}</span></div></div></section>
        <section class="daily"><h4>Xu hướng theo ngày</h4><div class="bars"><div v-for="item in data.byDay" :key="item.name" class="bar-row"><span>{{ date(item.name) }}</span><i><b :style="{width:barWidth(item.requests)}" /></i><strong>{{ item.requests }} lượt</strong><small>{{ cost(item.costMicros) }}</small></div></div></section>
      </div>
    </template>
  </section>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue';import { api } from '@/api/index';
type Group={name:string;requests:number;inputTokens:number;outputTokens:number;cachedInputTokens:number;costMicros:string;errors:number;p95LatencyMs:number|null};type Usage={hasData:boolean;totals:{requests:number;inputTokens:number;outputTokens:number;cachedInputTokens:number;costMicros:string;errors:number;p50LatencyMs:number|null;p95LatencyMs:number|null};byModel:Group[];byTask:Group[];byDay:Group[]};
const to=ref(new Date().toISOString().slice(0,10)),from=ref(new Date(Date.now()-29*86_400_000).toISOString().slice(0,10)),data=ref<Usage|null>(null),loading=ref(false),error=ref('');
const number=(v:number)=>v.toLocaleString('vi-VN');const cost=(v:string)=>`${BigInt(v||'0').toLocaleString('vi-VN')} µ`;const latency=(v:number|null)=>v==null?'—':`${v.toLocaleString('vi-VN')} ms`;const date=(v:string)=>new Date(v+'T00:00:00').toLocaleDateString('vi-VN');const barWidth=(v:number)=>`${Math.max(3,Math.round(v/Math.max(1,...(data.value?.byDay.map(x=>x.requests)||[1]))*100))}%`;
async function load(){loading.value=true;error.value='';try{data.value=(await api.get<Usage>('/ai/admin-center/usage',{params:{from:from.value,to:to.value}})).data}catch(e:any){error.value=e?.response?.data?.error||'Không thể tải dữ liệu sử dụng'}finally{loading.value=false}}onMounted(load);
</script>
<style scoped>
.usage-panel{display:grid;gap:16px}.panel-head{display:flex;justify-content:space-between;gap:16px}.panel-head h3{margin:0;font-size:20px;color:#172033}.panel-head p{margin:5px 0 0;color:#64748b}.panel-head button,.filters button{border:1px solid #cbd5e1;border-radius:8px;background:#fff;padding:9px 12px;color:#334155;cursor:pointer}.filters{display:flex;align-items:end;gap:10px;padding:13px;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc}.filters label{display:grid;gap:5px;color:#475569;font-weight:650}.filters input{min-height:38px;border:1px solid #cbd5e1;border-radius:7px;padding:7px 9px}.metrics{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}.metrics article{display:grid;gap:5px;padding:14px;border:1px solid #e2e8f0;border-radius:10px;background:#fff}.metrics span,.metrics small{color:#64748b}.metrics strong{font-size:22px;color:#172033}.state{display:grid;gap:5px;padding:24px;border:1px dashed #cbd5e1;border-radius:10px;text-align:center;color:#64748b}.state.error{border-color:#fecaca;background:#fff1f2;color:#991b1b}.grids{display:grid;grid-template-columns:1.25fr 1fr;gap:14px}.grids section{overflow:hidden;border:1px solid #e2e8f0;border-radius:10px;background:#fff}.grids h4{margin:0;padding:13px 15px;border-bottom:1px solid #e2e8f0;color:#172033}.daily{grid-column:1/-1}.table{display:grid}.row{display:grid;grid-template-columns:minmax(180px,1.5fr) repeat(4,minmax(80px,.7fr));gap:10px;padding:10px 15px;border-bottom:1px solid #f1f5f9;align-items:center}.row.task{grid-template-columns:minmax(140px,1.5fr) repeat(3,minmax(80px,.7fr))}.row.head{background:#f8fafc;color:#64748b;font-weight:700}.row strong{overflow:hidden;text-overflow:ellipsis}.bars{display:grid;gap:11px;padding:15px}.bar-row{display:grid;grid-template-columns:100px 1fr 70px 100px;gap:10px;align-items:center}.bar-row i{height:10px;overflow:hidden;border-radius:999px;background:#e2e8f0}.bar-row b{display:block;height:100%;border-radius:999px;background:#2563eb}.bar-row small{color:#64748b;text-align:right}@media(max-width:1100px){.metrics{grid-template-columns:repeat(3,1fr)}.grids{grid-template-columns:1fr}.daily{grid-column:auto}}@media(max-width:700px){.filters{align-items:stretch;flex-direction:column}.metrics{grid-template-columns:1fr 1fr}.row{grid-template-columns:1fr 70px}.row>*:nth-child(3),.row>*:nth-child(4),.row.task>*:nth-child(3){display:none}.bar-row{grid-template-columns:80px 1fr 60px}.bar-row small{display:none}}
</style>
